const pokemons = [
  {
    name: "Moltres",
    // image: "https://img.pokemondb.net/artwork/moltres.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0146.png",
    type: ["Fire", "Flying"],
    ability: "Pressure",
    hp: 90,
    attack: 100,
    defense: 90,
    spAttack: 125,
    spDefense: 85,
    speed: 90,
    baseHp: 90,
    baseAttack: 100,
    baseDefense: 90,
    baseSpAttack: 125,
    baseSpDefense: 85,
    baseSpeed: 90,
    moves: [flamethrower, airCutter, calmMind, roost],
    status: "alive",
  },
  {
    name: "Charizard",
    // image: "https://img.pokemondb.net/artwork/charizard.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0006.png",
    type: ["Fire", "Flying"],
    ability: "Blaze",
    hp: 78,
    attack: 84,
    defense: 78,
    spAttack: 109,
    spDefense: 85,
    speed: 100,
    baseHp: 78,
    baseAttack: 84,
    baseDefense: 78,
    baseSpAttack: 109,
    baseSpDefense: 85,
    baseSpeed: 100,
    moves: [dragonPulse, flamethrower, wingAttack, airCutter],
    status: "alive",
  },
  {
    name: "Blastoise",
    // image: "https://img.pokemondb.net/artwork/blastoise.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0009.png",

    type: ["Water"],
    ability: "Torrent",
    hp: 79,
    attack: 83,
    defense: 100,
    spAttack: 85,
    spDefense: 105,
    speed: 78,
    baseHp: 79,
    baseAttack: 83,
    baseDefense: 100,
    baseSpAttack: 85,
    baseSpDefense: 105,
    baseSpeed: 78,
    moves: [scald, iceBeam, aquaRing, bodySlam],
    status: "alive",
  },
  {
    name: "Snorlax",
    // image: "https://img.pokemondb.net/artwork/snorlax.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0143.png",

    type: ["Normal"],
    ability: "Immunity",
    hp: 160,
    attack: 110,
    defense: 65,
    spAttack: 65,
    spDefense: 110,
    speed: 30,
    baseHp: 160,
    baseAttack: 110,
    baseDefense: 65,
    baseSpAttack: 65,
    baseSpDefense: 110,
    baseSpeed: 30,
    moves: [bodySlam, hyperVoice, bulkUp, thunderPunch],
    status: "alive",
  },
  {
    name: "Mewtwo",
    // image: "https://img.pokemondb.net/artwork/mewtwo.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0150.png",

    type: ["Psychic"],
    ability: "Pressure",
    hp: 106,
    attack: 110,
    defense: 90,
    spAttack: 154,
    spDefense: 90,
    speed: 130,
    baseHp: 106,
    baseAttack: 110,
    baseDefense: 90,
    baseSpAttack: 154,
    baseSpDefense: 90,
    baseSpeed: 130,
    moves: [psychic, shadowBall, calmMind, auraSphere],
    status: "alive",
  },
  {
    name: "Gyarados",
    // image: "https://img.pokemondb.net/artwork/gyarados.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0130.png",

    type: ["Water", "Flying"],
    ability: "Intimidate",
    hp: 95,
    attack: 125,
    defense: 79,
    spAttack: 60,
    spDefense: 100,
    speed: 81,
    baseHp: 95,
    baseAttack: 125,
    baseDefense: 79,
    baseSpAttack: 60,
    baseSpDefense: 100,
    baseSpeed: 81,
    moves: [dragonDance, dragonClaw, scald, quickAttack],
    status: "alive",
  },
  {
    name: "Machamp",
    // image: "https://img.pokemondb.net/artwork/machamp.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0068.png",

    type: ["Fighting"],
    ability: "Guts",
    hp: 90,
    attack: 130,
    defense: 80,
    spAttack: 65,
    spDefense: 85,
    speed: 55,
    baseHp: 90,
    baseAttack: 130,
    baseDefense: 80,
    baseSpAttack: 65,
    baseSpDefense: 85,
    baseSpeed: 55,
    moves: [bulkUp, drainPunch, thunderPunch, firePunch],
    status: "alive",
  },
  {
    name: "Alakazam",
    // image: "https://img.pokemondb.net/artwork/alakazam.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0065.png",

    type: ["Psychic"],
    ability: "Synchronize",
    hp: 55,
    attack: 50,
    defense: 45,
    spAttack: 135,
    spDefense: 85,
    speed: 120,
    baseHp: 55,
    baseAttack: 50,
    baseDefense: 45,
    baseSpAttack: 135,
    baseSpDefense: 85,
    baseSpeed: 120,
    moves: [psychic, shadowBall, calmMind, signalBeam],
    status: "alive",
  },

  {
    name: "Rhydon",
    type: ["Rock", "Ground"],
    ability: "Lightning Rod",
    // image: "https://img.pokemondb.net/artwork/rhydon.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0112.png",

    hp: 105,
    attack: 130,
    defense: 120,
    spAttack: 45,
    spDefense: 45,
    speed: 40,
    baseHp: 105,
    baseAttack: 130,
    baseDefense: 120,
    baseSpAttack: 45,
    baseSpDefense: 45,
    baseSpeed: 40,
    moves: [earthquake, stoneEdge, hammerArm, rockSlide],
    status: "alive",
  },
  {
    name: "Arcanine",
    type: ["Fire"],
    ability: "Intimidate",
    // image: "https://img.pokemondb.net/artwork/arcanine.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0059.png",

    hp: 90,
    attack: 110,
    defense: 80,
    spAttack: 100,
    spDefense: 80,
    speed: 95,
    baseHp: 90,
    baseAttack: 110,
    baseDefense: 80,
    baseSpAttack: 100,
    baseSpDefense: 80,
    baseSpeed: 95,
    moves: [flamethrower, wildCharge, extremeSpeed, crunch],
    status: "alive",
  },
  {
    name: "Dragonite",
    type: ["Dragon", "Flying"],
    ability: "Inner Focus",
    // image: "https://img.pokemondb.net/artwork/dragonite.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0149.png",

    hp: 91,
    attack: 134,
    defense: 95,
    spAttack: 100,
    spDefense: 100,
    speed: 80,
    baseHp: 91,
    baseAttack: 134,
    baseDefense: 95,
    baseSpAttack: 100,
    baseSpDefense: 100,
    baseSpeed: 80,
    moves: [dragonClaw, fly, firePunch, thunderPunch],
    status: "alive",
  },
  {
    name: "Lugia",
    type: ["Psychic", "Flying"],
    ability: "Pressure",
    // image: "https://img.pokemondb.net/artwork/lugia.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0249.png",

    hp: 106,
    attack: 90,
    defense: 130,
    spAttack: 90,
    spDefense: 154,
    speed: 110,
    baseHp: 106,
    baseAttack: 90,
    baseDefense: 130,
    baseSpAttack: 90,
    baseSpDefense: 154,
    baseSpeed: 110,
    moves: [aeroblast, psychic, recover, calmMind],
    status: "alive",
  },
  {
    name: "Pidgeot",
    type: ["Normal", "Flying"],
    ability: "Big Pecks",
    // image: "https://img.pokemondb.net/artwork/pidgeot.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0018.png",

    hp: 83,
    attack: 80,
    defense: 75,
    spAttack: 70,
    spDefense: 70,
    speed: 101,
    baseHp: 83,
    baseAttack: 80,
    baseDefense: 75,
    baseSpAttack: 70,
    baseSpDefense: 70,
    baseSpeed: 101,
    moves: [braveBird, airSlash, heatWave, uTurn],
    status: "alive",
  },
  {
    name: "Venusaur",
    type: ["Grass", "Poison"],
    ability: "Overgrow",
    // image: "https://img.pokemondb.net/artwork/venusaur.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0003.png",

    hp: 80,
    attack: 82,
    defense: 83,
    spAttack: 100,
    spDefense: 100,
    speed: 80,
    baseHp: 80,
    baseAttack: 82,
    baseDefense: 83,
    baseSpAttack: 100,
    baseSpDefense: 100,
    baseSpeed: 80,
    moves: [solarBeam, sludgeBomb, earthquake, synthesis],
    status: "alive",
  },
  // {
  //   name: "Blissey",
  //   type: ["Normal"],
  //   ability: "Serene Grace",
  //   // image: "https://img.pokemondb.net/artwork/blissey.jpg",
  //   image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0113.png",

  //   hp: 255,
  //   attack: 70,
  //   defense: 70,
  //   spAttack: 95,
  //   spDefense: 135,
  //   speed: 55,
  //   baseHp: 255,
  //   baseAttack: 70,
  //   baseDefense: 70,
  //   baseSpAttack: 95,
  //   baseSpDefense: 135,
  //   baseSpeed: 55,
  //   moves: [softBoiled, seismicToss, thunderWave, healBell],
  //   status: "alive",
  // },
  {
    name: "Gengar",
    type: ["Ghost", "Poison"],
    ability: "Levitate",
    // image: "https://img.pokemondb.net/artwork/gengar.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0094.png",

    hp: 60,
    attack: 65,
    defense: 60,
    spAttack: 130,
    spDefense: 75,
    speed: 110,
    baseHp: 60,
    baseAttack: 65,
    baseDefense: 60,
    baseSpAttack: 130,
    baseSpDefense: 75,
    baseSpeed: 110,
    moves: [shadowBall, sludgeBomb, willOWisp, thunderbolt],
    status: "alive",
  },
  {
    name: "Heracross",
    type: ["Bug", "Fighting"],
    ability: "Guts",
    // image: "https://img.pokemondb.net/artwork/heracross.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0214.png",

    hp: 80,
    attack: 125,
    defense: 75,
    spAttack: 40,
    spDefense: 95,
    speed: 85,
    baseHp: 80,
    baseAttack: 125,
    baseDefense: 75,
    baseSpAttack: 40,
    baseSpDefense: 95,
    baseSpeed: 85,
    moves: [closeCombat, megahorn, stoneEdge, swordsDance],
    status: "alive",
  },
  {
    name: "Tyranitar",
    type: ["Rock", "Dark"],
    ability: "Sand Stream",
    // image: "https://img.pokemondb.net/artwork/tyranitar.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0248.png",

    hp: 100,
    attack: 134,
    defense: 110,
    spAttack: 95,
    spDefense: 100,
    speed: 61,
    baseHp: 100,
    baseAttack: 134,
    baseDefense: 110,
    baseSpAttack: 95,
    baseSpDefense: 100,
    baseSpeed: 61,
    moves: [crunch, stoneEdge, iceBeam, pursuit],
    status: "alive",
  },
  {
    name: "Ferrothorn",
    type: ["Grass", "Steel"],
    ability: "Iron Barbs",
    // image: "https://img.pokemondb.net/artwork/ferrothorn.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0598.png",

    hp: 74,
    attack: 94,
    defense: 131,
    spAttack: 54,
    spDefense: 116,
    speed: 20,
    baseHp: 74,
    baseAttack: 94,
    baseDefense: 131,
    baseSpAttack: 54,
    baseSpDefense: 116,
    baseSpeed: 20,
    moves: [leechSeed, stealthRock, gyroBall, powerWhip],
    status: "alive",
  },
  {
    name: "Sableye",
    type: ["Dark", "Ghost"],
    ability: "Prankster",
    // image: "https://img.pokemondb.net/artwork/sableye.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0302.png",

    hp: 50,
    attack: 75,
    defense: 75,
    spAttack: 65,
    spDefense: 65,
    speed: 50,
    baseHp: 50,
    baseAttack: 75,
    baseDefense: 75,
    baseSpAttack: 65,
    baseSpDefense: 65,
    baseSpeed: 50,
    moves: [foulPlay, shadowClaw, willOWisp, recover],
    status: "alive",
  },
  {
    name: "Zoroark",
    type: ["Dark"],
    ability: "Illusion",
    // image: "https://img.pokemondb.net/artwork/zoroark.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0571.png",

    hp: 60,
    attack: 105,
    defense: 60,
    spAttack: 120,
    spDefense: 60,
    speed: 105,
    baseHp: 60,
    baseAttack: 105,
    baseDefense: 60,
    baseSpAttack: 120,
    baseSpDefense: 60,
    baseSpeed: 105,
    moves: [nightDaze, foulPlay, uTurn, flamethrower],
    status: "alive",
  },
  {
    name: "Lucario",
    type: ["Fighting", "Steel"],
    ability: "Justified",
    // image: "https://img.pokemondb.net/artwork/lucario.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0448.png",

    hp: 70,
    attack: 110,
    defense: 70,
    spAttack: 115,
    spDefense: 70,
    speed: 90,
    baseHp: 70,
    baseAttack: 110,
    baseDefense: 70,
    baseSpAttack: 115,
    baseSpDefense: 70,
    baseSpeed: 90,
    moves: [auraSphere, flashCannon, crunch, extremeSpeed],
    status: "alive",
  },
  {
    name: "Scizor",
    type: ["Bug", "Steel"],
    ability: "Technician",
    // image: "https://img.pokemondb.net/artwork/scizor.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0212.png",

    hp: 70,
    attack: 130,
    defense: 100,
    spAttack: 55,
    spDefense: 80,
    speed: 65,
    baseHp: 70,
    baseAttack: 130,
    baseDefense: 100,
    baseSpAttack: 55,
    baseSpDefense: 80,
    baseSpeed: 65,
    moves: [bulletPunch, xScissor, swordsDance, pursuit],
    status: "alive",
  },
  {
    name: "Crobat",
    type: ["Poison", "Flying"],
    hp: 85,
    attack: 90,
    defense: 80,
    spAttack: 70,
    spDefense: 80,
    speed: 130,
    ability: "Infiltrator",
    // image: "https://img.pokemondb.net/artwork/crobat.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0169.png",

    moves: [braveBird, crossPoison, uTurn, toxic],
    status: "alive",
    baseHp: 85,
    baseAttack: 90,
    baseDefense: 80,
    baseSpAttack: 70,
    baseSpDefense: 80,
    baseSpeed: 130,
  },
  {
    name: "Magnezone",
    type: ["Electric", "Steel"],
    hp: 70,
    attack: 60,
    defense: 115,
    spAttack: 130,
    spDefense: 90,
    speed: 60,
    ability: "Magnet Pull",
    // image: "https://img.pokemondb.net/artwork/magnezone.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0462.png",

    moves: [thunderbolt, flashCannon, signalBeam, magnetRise],
    status: "alive",
    baseHp: 70,
    baseAttack: 60,
    baseDefense: 115,
    baseSpAttack: 130,
    baseSpDefense: 90,
    baseSpeed: 60,
  },
  {
    name: "Salamence",
    type: ["Dragon", "Flying"],
    hp: 95,
    attack: 135,
    defense: 80,
    spAttack: 110,
    spDefense: 80,
    speed: 100,
    ability: "Intimidate",
    // image: "https://img.pokemondb.net/artwork/salamence.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0373.png",

    moves: [outrage, dragonClaw, fly, fireBlast],
    status: "alive",
    baseHp: 95,
    baseAttack: 135,
    baseDefense: 80,
    baseSpAttack: 110,
    baseSpDefense: 80,
    baseSpeed: 100,
  },
  {
    name: "Excadrill",
    type: ["Steel", "Ground"],
    hp: 110,
    attack: 135,
    defense: 60,
    spAttack: 50,
    spDefense: 65,
    speed: 88,
    ability: "Mold Breaker",
    // image: "https://img.pokemondb.net/artwork/excadrill.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0530.png",

    moves: [earthquake, ironHead, stealthRock, toxic],
    status: "alive",
    baseHp: 110,
    baseAttack: 135,
    baseDefense: 60,
    baseSpAttack: 50,
    baseSpDefense: 65,
    baseSpeed: 88,
  },
  {
    name: "Volcarona",
    type: ["Bug", "Fire"],
    hp: 85,
    attack: 60,
    defense: 65,
    spAttack: 135,
    spDefense: 105,
    speed: 100,
    ability: "Flame Body",
    // image: "https://img.pokemondb.net/artwork/volcarona.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0637.png",

    moves: [fieryDance, bugBuzz, quiverDance, roost],
    status: "alive",
    baseHp: 85,
    baseAttack: 60,
    baseDefense: 65,
    baseSpAttack: 135,
    baseSpDefense: 105,
    baseSpeed: 100,
  },
  {
    name: "Haxorus",
    type: ["Dragon"],
    hp: 76,
    attack: 147,
    defense: 90,
    spAttack: 60,
    spDefense: 70,
    speed: 97,
    ability: "Mold Breaker",
    // image: "https://img.pokemondb.net/artwork/haxorus.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0612.png",

    moves: [outrage, dragonClaw, earthquake, swordsDance],
    status: "alive",
    baseHp: 76,
    baseAttack: 147,
    baseDefense: 90,
    baseSpAttack: 60,
    baseSpDefense: 70,
    baseSpeed: 97,
  },
  {
    name: "Garchomp",
    type: ["Dragon", "Ground"],
    hp: 108,
    attack: 130,
    defense: 95,
    spAttack: 80,
    spDefense: 85,
    speed: 102,
    ability: "Rough Skin",
    // image: "https://img.pokemondb.net/artwork/garchomp.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0445.png",

    moves: [earthquake, dragonClaw, stoneEdge, swordsDance],
    status: "alive",
    baseHp: 108,
    baseAttack: 130,
    baseDefense: 95,
    baseSpAttack: 80,
    baseSpDefense: 85,
    baseSpeed: 102,
  },
  {
    name: "Togekiss",
    type: ["Normal", "Flying"],
    hp: 85,
    attack: 50,
    defense: 95,
    spAttack: 120,
    spDefense: 115,
    speed: 80,
    ability: "Serene Grace",
    // image: "https://img.pokemondb.net/artwork/togekiss.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0468.png",

    moves: [airSlash, auraSphere, thunderWave, roost],
    status: "alive",
    baseHp: 85,
    baseAttack: 50,
    baseDefense: 95,
    baseSpAttack: 120,
    baseSpDefense: 115,
    baseSpeed: 80,
  },
  {
    name: "Gliscor",
    type: ["Ground", "Flying"],
    hp: 75,
    attack: 95,
    defense: 125,
    spAttack: 45,
    spDefense: 75,
    speed: 95,
    ability: "Poison Heal",
    // image: "https://img.pokemondb.net/artwork/gliscor.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0472.png",

    moves: [earthquake, toxic, roost, aerialAce],
    status: "alive",
    baseHp: 75,
    baseAttack: 95,
    baseDefense: 125,
    baseSpAttack: 45,
    baseSpDefense: 75,
    baseSpeed: 95,
  },
  {
    name: "Incineroar",
    type: ["Fire", "Dark"],
    hp: 95,
    attack: 115,
    defense: 90,
    spAttack: 60,
    spDefense: 70,
    speed: 60,
    ability: "Intimidate",
    // image: "https://img.pokemondb.net/artwork/incineroar.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0727.png",

    moves: [flareBlitz, darkestLariat, fakeOut, snarl],
    status: "alive",
    baseHp: 95,
    baseAttack: 115,
    baseDefense: 90,
    baseSpAttack: 60,
    baseSpDefense: 70,
    baseSpeed: 60,
  },
  {
    name: "Sandslash",
    type: ["Ground"],
    hp: 75,
    attack: 100,
    defense: 110,
    spAttack: 45,
    spDefense: 55,
    speed: 65,
    ability: "Sand Rush",
    // image: "https://img.pokemondb.net/artwork/sandslash.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0028.png",

    moves: [earthquake, stealthRock, ironTail, toxic],
    status: "alive",
    baseHp: 75,
    baseAttack: 100,
    baseDefense: 110,
    baseSpAttack: 45,
    baseSpDefense: 55,
    baseSpeed: 65,
  },
  {
    name: "Lilligant",
    type: ["Grass"],
    hp: 70,
    attack: 60,
    defense: 75,
    spAttack: 110,
    spDefense: 75,
    speed: 90,
    ability: "Own Tempo",
    // image: "https://img.pokemondb.net/artwork/lilligant.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0549.png",

    moves: [solarBeam, quiverDance, gigaDrain, hiddenPower],
    status: "alive",
    baseHp: 70,
    baseAttack: 60,
    baseDefense: 75,
    baseSpAttack: 110,
    baseSpDefense: 75,
    baseSpeed: 90,
  },
  {
    name: "Seviper",
    type: ["Poison"],
    hp: 73,
    attack: 100,
    defense: 60,
    spAttack: 100,
    spDefense: 60,
    speed: 65,
    ability: "Infiltrator",
    // image: "https://img.pokemondb.net/artwork/seviper.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0336.png",

    moves: [toxic, poisonJab, swordsDance, flamethrower],
    status: "alive",
    baseHp: 73,
    baseAttack: 100,
    baseDefense: 60,
    baseSpAttack: 100,
    baseSpDefense: 60,
    baseSpeed: 65,
  },
  {
    name: "Abomasnow",
    type: ["Grass", "Ice"],
    hp: 90,
    attack: 92,
    defense: 75,
    spAttack: 92,
    spDefense: 85,
    speed: 60,
    ability: "Snow Warning",
    // image: "https://img.pokemondb.net/artwork/abomasnow.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0460.png",

    moves: [blizzard, woodHammer, iceShard, leechSeed],
    status: "alive",
    baseHp: 90,
    baseAttack: 92,
    baseDefense: 75,
    baseSpAttack: 92,
    baseSpDefense: 85,
    baseSpeed: 60,
  },
  {
    name: "Chandelure",
    type: ["Ghost", "Fire"],
    hp: 60,
    attack: 55,
    defense: 90,
    spAttack: 145,
    spDefense: 90,
    speed: 80,
    ability: "Infiltrator",
    // image: "https://img.pokemondb.net/artwork/chandelure.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0609.png",

    moves: [shadowBall, flamethrower, willOWisp, energyBall],
    status: "alive",
    baseHp: 60,
    baseAttack: 55,
    baseDefense: 90,
    baseSpAttack: 145,
    baseSpDefense: 90,
    baseSpeed: 80,
  },
  {
    name: "Claydol",
    type: ["Ground", "Psychic"],
    hp: 60,
    attack: 70,
    defense: 105,
    spAttack: 70,
    spDefense: 120,
    speed: 75,
    ability: "Levitate",
    // image: "https://img.pokemondb.net/artwork/claydol.jpg",
    image: "images/pokemonGen7/Gen7/ultra-sun-ultra-moon/0344.png",

    moves: [earthPower, psychic, stealthRock, rapidSpin],
    status: "alive",
    baseHp: 60,
    baseAttack: 70,
    baseDefense: 105,
    baseSpAttack: 70,
    baseSpDefense: 120,
    baseSpeed: 75,
  },
];
